services:
  - type: web
    name: photopixel-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://photopixel-frontend.onrender.com
      - key: PORT
        value: 10000

  - type: web
    name: photopixel-frontend
    env: static
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://photopixel-backend.onrender.com/api